name: project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  url_launcher: ^6.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.9
  sqflite: ^2.2.0+3
  path_provider: ^2.0.11


  google_maps_flutter: ^2.4.0
  location: ^5.0.3
  flutter_local_notifications: ^15.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
