version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: u-22
    container_name: backend
    hostname: backend
    volumes:
      - ../:/work
    ports:
      - 5001:5001
    tty: true
