version: '3'

services:
  backend:
    env_file: .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    hostname: ${HOST_NAME}
    volumes:
      - /Users/${USERNAME}/.ssh:/root/.ssh
      # - ../:/home/${USERNAME}
    ports:
      - 5001:5001
    tty: true
